#!/bin/sh
# Check the battery capacity and current time and append to
# ~/.local/share/battery-life.csv
# Designed to be run as a cron job.

capacity=$(cat /sys/class/power_supply/BAT0/capacity)
time=$(date)

export DBUS_SESSION_BUS_ADDRESS=unix:path=/rub/user/1000/bus; export DISPLAY=:0; . $HOME/.profile &&
echo "$time,$capacity" >> $HOME/.local/share/battery-life.csv &&
notify-send "Battery life updated!"
